variable "aws_region" {}
variable "vpc_cidr" {}
variable "vpc_name" {}
variable "key_name" {}
variable "public_subnet_cidrs" {}
variable "private_subnet_cidrs" {}
variable "azs" {}
variable "environment" {}
variable "instance_type" {}
variable "imagename" {}
variable "owner" {}
variable "ingress_ports" {}
variable "egress_ports" {}
variable "appversion" {}